<?php

namespace App\Infrastructure\AI;

use App\Domain\Chat\Contracts\AIProviderInterface;
use App\Domain\Chat\DataObjects\ChatResult;

/**
 * Keyless, deterministic AI provider used as the default fallback.
 *
 * - chat() composes a grounded answer from the retrieved context that the
 *   RagChatService injects as a system message, so the demo experience reads
 *   like a real RAG assistant without any external API.
 * - embed() is a lexical hashing vectorizer: texts sharing words produce
 *   similar vectors, so cosine-similarity retrieval returns sensible results.
 */
class MockProvider implements AIProviderInterface
{
    private const DIMENSIONS = 256;

    private const MODEL = 'mock-embedding-v1';

    public function chat(array $messages, array $options = []): ChatResult
    {
        $question = $this->lastUserMessage($messages);
        $context = $this->extractContext($messages);

        $answer = $context !== ''
            ? $this->groundedAnswer($question, $context)
            : $this->genericAnswer($question);

        return new ChatResult(
            content: $answer,
            model: 'mock-chat-v1',
            promptTokens: (int) ceil(mb_strlen(implode(' ', array_column($messages, 'content'))) / 4),
            completionTokens: (int) ceil(mb_strlen($answer) / 4),
            raw: ['provider' => 'mock'],
        );
    }

    public function embed(array $texts): array
    {
        return array_map(fn (string $text) => $this->hashVector($text), $texts);
    }

    public function embeddingDimensions(): int
    {
        return self::DIMENSIONS;
    }

    public function embeddingModel(): string
    {
        return self::MODEL;
    }

    public function name(): string
    {
        return 'mock';
    }

    public function isAvailable(): bool
    {
        return true;
    }

    private function groundedAnswer(string $question, string $context): string
    {
        $snippet = $this->firstSentences($context, 3);

        return 'Based on the available course materials, here is what I found'
            .($question !== '' ? " regarding \"{$question}\"" : '').":\n\n"
            .$snippet."\n\n"
            .'This response is grounded in the cited sources below. For full detail, '
            .'open the referenced documents. *(Demo response generated by the built-in '
            .'mock AI provider — set OPENAI_API_KEY and AI_DEFAULT_PROVIDER=openai for live answers.)*';
    }

    private function genericAnswer(string $question): string
    {
        $topic = $question !== '' ? " about \"{$question}\"" : '';

        return "I don't have an approved course document that directly covers this, but I can still "
            ."help{$topic} from general academic knowledge.\n\n"
            .'Tell me a bit more about what you want to achieve — for example a concept to explain, a '
            .'topic to study, or a problem to work through — and I\'ll guide you step by step. If this '
            .'relates to one of your enrolled courses, mention it and I\'ll tailor the answer.'
            ."\n\n*(Demo response from the built-in mock AI provider — set OPENAI_API_KEY and "
            .'AI_DEFAULT_PROVIDER=openai for full, live answers.)*';
    }

    private function lastUserMessage(array $messages): string
    {
        for ($i = count($messages) - 1; $i >= 0; $i--) {
            if (($messages[$i]['role'] ?? '') === 'user') {
                return trim((string) ($messages[$i]['content'] ?? ''));
            }
        }

        return '';
    }

    private function extractContext(array $messages): string
    {
        foreach ($messages as $message) {
            $content = (string) ($message['content'] ?? '');
            if (($message['role'] ?? '') === 'system' && str_contains($content, 'Context:')) {
                return trim(substr($content, strpos($content, 'Context:') + 8));
            }
        }

        return '';
    }

    private function firstSentences(string $text, int $count): string
    {
        $text = preg_replace('/\s+/', ' ', trim($text)) ?? $text;
        $parts = preg_split('/(?<=[.!?])\s+/', $text) ?: [$text];

        return trim(implode(' ', array_slice($parts, 0, $count)));
    }

    /**
     * Deterministic lexical hashing embedding (bag-of-words → fixed dims, L2-normalized).
     *
     * @return array<int, float>
     */
    private function hashVector(string $text): array
    {
        $vector = array_fill(0, self::DIMENSIONS, 0.0);

        preg_match_all('/[a-z0-9]+/', mb_strtolower($text), $matches);
        foreach ($matches[0] as $token) {
            if (mb_strlen($token) < 2) {
                continue;
            }
            $bucket = crc32($token) % self::DIMENSIONS;
            $vector[$bucket] += 1.0;
        }

        $norm = sqrt(array_sum(array_map(fn ($v) => $v * $v, $vector)));
        if ($norm > 0) {
            $vector = array_map(fn ($v) => $v / $norm, $vector);
        }

        return $vector;
    }
}
